alter table ACTIVITY_LOG
add ACT_LOGIN_USER varchar(100)


alter table ACTIVITY_LOG
ADD ACT_ADMISSIONNO INT;

ALTER TABLE dbo.STUDENT_FACILITIES ADD
	STFL_DISCOUNT_REASON varchar(400) NULL;

	
alter table student_master 
add STMT_SOURCE varchar(50);

ALTER TABLE STUDENT_MASTER
 ADD STMT_HEATH_ISSUE VARCHAR(500)


 INSERT [dbo].[FUNCTION_MASTER] ([FM_ID], [FM_NAME], [FM_SHORT_KEY], [FM_HOT_KEY], [FM_FORM_CLASS], [FM_FORM_ASSEMBLY], [FM_LEVEL_INDCTR], [FM_PARENT_ID], [FM_GRP_SEQ], [FM_APP_NAME], [FM_BRANCH_ID], [FM_CRTD_AT], [FM_UPDT_AT], [FM_DLTD_AT], [FM_CRTD_BY], [FM_UPDAT_BY], [FM_DLTD_BY], [ID]) VALUES (98, N'Birthday Report', N'B', N'R', N'FrmBirthdayReport', N'ClassesManager.WinApp', N'L', 91, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 94)


INSERT [dbo].[FUNCTION_MASTER] ([FM_ID], [FM_NAME], [FM_SHORT_KEY], [FM_HOT_KEY], [FM_FORM_CLASS], [FM_FORM_ASSEMBLY], [FM_LEVEL_INDCTR], [FM_PARENT_ID], [FM_GRP_SEQ], [FM_APP_NAME], [FM_BRANCH_ID], [FM_CRTD_AT], [FM_UPDT_AT], [FM_DLTD_AT], [FM_CRTD_BY], [FM_UPDAT_BY], [FM_DLTD_BY], [ID]) VALUES (99, N'Followup Details', N'F', N'D', N'FrmFollowupDetails', N'ClassesManager.WinApp', N'L', 86, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 95)

 INSERT [dbo].[FUNCTION_MASTER] ([FM_ID], [FM_NAME], [FM_SHORT_KEY], [FM_HOT_KEY], [FM_FORM_CLASS], [FM_FORM_ASSEMBLY], [FM_LEVEL_INDCTR], [FM_PARENT_ID], [FM_GRP_SEQ], [FM_APP_NAME], [FM_BRANCH_ID], [FM_CRTD_AT], [FM_UPDT_AT], [FM_DLTD_AT], [FM_CRTD_BY], [FM_UPDAT_BY], [FM_DLTD_BY], [ID]) VALUES (100, N'Activity Report', N'A', N'R', N'FrmActivityDetails', N'ClassesManager.WinApp', N'L', 9, 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 96)

alter table branch_master add NOTIFICATION_SENT_DATE varchar(50);




        create table MEASUREMENTS
		( MM_MID int,
            MM_ADMISSION_NO int,          
            MM_WEIGHT decimal(18,2),
            MM_BMI decimal(18,2),
            MM_HEIGHT decimal(18,2),
            MM_FAT decimal(18,2),
            MM_NECK decimal(18,2),
            MM_SHOULDER decimal(18,2),
            MM_CHEST decimal(18,2),
            MM_ARMS decimal(18,2),
            MM_HIPS decimal(18,2),
            MM_THIGH decimal(18,2),
            MM_CALVES decimal(18,2),
            MM_FOREARMS decimal(18,2),
            MM_UPPER_ABD decimal(18,2),
            MM_LOWER_ABD decimal(18,2),
            MM_WAIST decimal(18,2),
			MM_ID int identity,
			MM_DATE datetime,
			MM_BRANCHID varchar(50)
			)



USE [Gymwise1.3]
GO
/****** Object:  Trigger [dbo].[TRG_student_measurement_AFTER_INSERT]    Script Date: 19/01/21 3:44:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TRIGGER [dbo].[TRG_STUD_MEASUREMENT_AFTR_INSRT] ON [dbo].[MEASUREMENTS]
AFTER INSERT
AS
BEGIN
	DECLARE @newid INT
	DECLARE @id INT
	DECLARE @branchid INT

	SET @id = (
			SELECT MM_ID
			FROM inserted
			);
	SET @branchid = (
			SELECT MM_BRANCHID
			FROM inserted
			);
	SET @newid = CONVERT(INT, CONVERT(NVARCHAR, @branchid) + CONVERT(NVARCHAR, @id));

	IF (@newid IS NOT NULL)
		UPDATE MEASUREMENTS
		SET MM_MID = @newid
		WHERE MM_ID = @id
			AND MM_BRANCHID= @branchid
END



drop foreign key from facility_update table.FK_FACILITY_UPDATE_STUDENT_FACILITIES

INSERT [dbo].[SYSTEM_PRM] ([PRM_NAME], [PRM_VALUE], [PRM_VALUE_INT], [PRM_FRM_DT], [PRM_TO_DT], [PRM_BRANCH_ID], [PRM_CRTD_AT], [PRM_UPDT_AT], [PRM_DLTD_AT], [PRM_CRTD_BY], [PRM_UPDAT_BY], [PRM_DLTD_BY], [PRM_VISIBILITY_ROLE_ID], [ID], [NOTIFICATION_SENT_DATE]) VALUES (N'SEND_TOBE_EXPIRY_MSG', N'True', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1125, NULL)
INSERT [dbo].[SYSTEM_PRM] ([PRM_NAME], [PRM_VALUE], [PRM_VALUE_INT], [PRM_FRM_DT], [PRM_TO_DT], [PRM_BRANCH_ID], [PRM_CRTD_AT], [PRM_UPDT_AT], [PRM_DLTD_AT], [PRM_CRTD_BY], [PRM_UPDAT_BY], [PRM_DLTD_BY], [PRM_VISIBILITY_ROLE_ID], [ID], [NOTIFICATION_SENT_DATE]) VALUES (N'BIO_EXP_COLOR', N'Blue', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1127, NULL)
INSERT [dbo].[SYSTEM_PRM] ([PRM_NAME], [PRM_VALUE], [PRM_VALUE_INT], [PRM_FRM_DT], [PRM_TO_DT], [PRM_BRANCH_ID], [PRM_CRTD_AT], [PRM_UPDT_AT], [PRM_DLTD_AT], [PRM_CRTD_BY], [PRM_UPDAT_BY], [PRM_DLTD_BY], [PRM_VISIBILITY_ROLE_ID], [ID], [NOTIFICATION_SENT_DATE]) VALUES (N'NOTIFY_EXPIRY', N'True', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1126, NULL)
INSERT [dbo].[SYSTEM_PRM] ([PRM_NAME], [PRM_VALUE], [PRM_VALUE_INT], [PRM_FRM_DT], [PRM_TO_DT], [PRM_BRANCH_ID], [PRM_CRTD_AT], [PRM_UPDT_AT], [PRM_DLTD_AT], [PRM_CRTD_BY], [PRM_UPDAT_BY], [PRM_DLTD_BY], [PRM_VISIBILITY_ROLE_ID], [ID], [NOTIFICATION_SENT_DATE]) VALUES (N'NOTIFY_PAKG_EXPIRY', N'7039691220', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1128, NULL)