USE [Gymwise1.3]
GO
/****** Object:  StoredProcedure [dbo].[s_pr_disp_outstng_fees]    Script Date: 19/01/22 6:44:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--Name : s_pr_disp_outstng_fees
--Developer : Hemlata
--Purpose : This Procedure is used to display the Students whose Fees Outstanding.
--Tables Used : STUDENT_MASTER,STUDENT_ADMISSION, INSTALLMENTS_DETAILS,STANDARD,STREAM,STUDENT_FACILITIES,BATCH ,BRANCH_MASTER(Select)
--SP Used : Sp_logerror
--Called From : FeesHandler.getOutstandingFees() in FrmOutstandingFees.
--Change History 
--removed todays due by ashvini on 17-01-2019
--rename admission no as ID by ashvini 17-01-2019
----------------------------------------------------------------------
--Date		Change		Perpose				Developer


ALTER PROCEDURE [dbo].[s_pr_disp_outstng_fees] (
	@Branch_Id VARCHAR(10)
	,@Date DATE
	,@stream varchar(50)
	,@course varchar (50)
	,@batch varchar(50)
	,@studentwise bit = true
	,@USER_ID VARCHAR(50) = 'SYSTEM'
	,@NUM_ERROR_CODE INT OUTPUT
	)
AS
BEGIN
	BEGIN TRY
	declare @appname varchar(50);
set @appname = (Select PRM_VALUE from SYSTEM_PRM where PRM_NAME = 'APPLICATION_NAME')

if(@studentwise = 1)
begin

		SELECT STUDENT_MASTER.STMT_ADMISSION_NO AS [ID]
				,STUDENT_MASTER.STMT_FNAME + ' ' + STUDENT_MASTER.STMT_LNAME AS NAME
				,ISNULL(SUM(INSTALLMENTS_DETAILS.INSD_INSTMNT_AMT) - SUM(INSTALLMENTS_DETAILS.INSD_AMOUNT_PAID) - SUM(INSTALLMENTS_DETAILS.INSD_DISCOUNT)-sum(ISNULL(INSD_CNCLD_AMT,0)), 0) AS [Total Outstanding]
				,STUDENT_MASTER.STMT_CONTACT_NO AS [Contact No]
				,STUDENT_MASTER.STMT_FATHER_CONTACT as [Parent's No]
				,STUDENT_MASTER.STMT_EMAIL_ID AS [Email ID]
			FROM STUDENT
			INNER JOIN STUDENT_MASTER ON STUDENT.STUD_ADMISSION_NO = STUDENT_MASTER.STMT_ADMISSION_NO
			INNER JOIN FEES ON STUDENT.STUD_FEES_ID = FEES.FEE_ID
			INNER JOIN INSTALLMENTS_DETAILS ON INSTALLMENTS_DETAILS.INSD_FEES_ID = FEES.FEE_ID
			WHERE (STUDENT_MASTER.STMT_BRANCH_ID LIKE @Branch_Id)
			GROUP BY STUDENT_MASTER.STMT_ADMISSION_NO
				,STUDENT_MASTER.STMT_FNAME + ' ' + STUDENT_MASTER.STMT_LNAME
				,STUDENT_MASTER.STMT_FATHER_CONTACT
				,STUDENT_MASTER.STMT_CONTACT_NO
				,STUDENT_MASTER.STMT_EMAIL_ID
			order by [Total Outstanding] desc
end;

else
begin

if @appname like '' or @appname like 'Gym' or @appname like 'Asset'
begin
		SELECT [ID]
			--,[Roll No]
			,Name
			,SUM([Fees Paid]) AS [Fees Paid]
			
			,SUM([Total Outstanding]) AS [Total Outstanding]
			,SUM([Total Fees]) AS [Total Fees]
			,SUM(Discount) AS Discount
			,sum([Cancelled Amount]) as CancelledAmount
			,STRM_NAME
			,STD_NAME 
			,[Package Name]
			,[Contact No]
			,[Parent No]
			,[Email ID]
			,Batch
			,Branch
			,STD_ID
			,STD_STREAM_ID
		FROM (
			SELECT STUDENT_MASTER.STMT_ADMISSION_NO AS [ID]
				--,STUDENT_ADMISSION.STAM_ROLL_NO AS [Roll No]
				,STUDENT_MASTER.STMT_FNAME + ' ' + STUDENT_MASTER.STMT_LNAME AS NAME
				,0 AS [Fees Paid]
				--,ISNULL(SUM(INSTALLMENTS_DETAILS.INSD_INSTMNT_AMT) - SUM(INSTALLMENTS_DETAILS.INSD_AMOUNT_PAID) - SUM(INSTALLMENTS_DETAILS.INSD_DISCOUNT)-sum(ISNULL(INSD_CNCLD_AMT,0)), 0) AS [Today Due]
				,0 AS [Total Outstanding]
				,0 AS [Total Fees]
				,0 AS Discount
				,0 as "Cancelled Amount"
				,STANDARD.STD_NAME 
				,STREAM.STRM_NAME 
				,STUDENT_FACILITIES.STFL_FACILITY_NAME AS [Package Name]
				,STUDENT_MASTER.STMT_CONTACT_NO as[Contact No]
				,STUDENT_MASTER.STMT_FATHER_CONTACT AS [Parent No]
				,STUDENT_MASTER.STMT_EMAIL_ID AS [Email ID]
				,BATCH.BTCH_NAME AS Batch
				,BRANCH_MASTER.BRCH_NAME AS Branch
				,STANDARD.STD_ID
				,STANDARD.STD_STREAM_ID
			FROM STUDENT
			INNER JOIN STUDENT_MASTER ON STUDENT.STUD_ADMISSION_NO = STUDENT_MASTER.STMT_ADMISSION_NO
			INNER JOIN BRANCH_MASTER ON STUDENT_MASTER.STMT_BRANCH_ID = BRANCH_MASTER.BRCH_ID
			INNER JOIN FEES ON STUDENT.STUD_FEES_ID = FEES.FEE_ID
			INNER JOIN STUDENT_ADMISSION ON STUDENT.STUD_ADMISSION_NO = STUDENT_ADMISSION.STAM_ADMISSION_NO
			INNER JOIN BATCH ON BATCH.BTCH_Id = STUDENT_ADMISSION.STAM_BATCH_ID
			INNER JOIN STANDARD ON STANDARD.STD_ID = STUDENT_ADMISSION.STAM_STD_ID
			INNER JOIN STREAM ON Standard.STD_STREAM_ID = STREAM.STRM_ID
			INNER JOIN STUDENT_FACILITIES ON STUDENT_ADMISSION.STAM_PACKAGE_ID = STUDENT_FACILITIES.STFL_PACKAGE_ID
				AND STUDENT_FACILITIES.STFL_ADMISSION_NO = STUDENT.STUD_ADMISSION_NO
			INNER JOIN INSTALLMENTS_DETAILS ON INSTALLMENTS_DETAILS.INSD_FACILITY_ID = STUDENT_FACILITIES.STFL_ID
			WHERE (STUDENT_MASTER.STMT_BRANCH_ID LIKE @Branch_Id)
			AND STREAM.STRM_ID like @stream 
			and STANDARD.STD_ID like @course
			and BATCH.BTCH_Id like @batch
		    AND INSTALLMENTS_DETAILS.INSD_DATE <= @Date
		  
			GROUP BY STUDENT_MASTER.STMT_ADMISSION_NO
				,BRANCH_MASTER.BRCH_NAME
				--,STUDENT_ADMISSION.STAM_ROLL_NO
				,STUDENT_MASTER.STMT_FNAME
				,STUDENT_MASTER.STMT_MNAME
				,STUDENT_MASTER.STMT_LNAME
				,STANDARD.STD_NAME
				,STREAM.STRM_NAME
				,STUDENT_MASTER.STMT_CONTACT_NO
				,STUDENT_MASTER.STMT_FATHER_CONTACT
				,STUDENT_MASTER.STMT_EMAIL_ID
				,BATCH.BTCH_NAME
				,STANDARD.STD_ID
				,STANDARD.STD_STREAM_ID
				,STUDENT_FACILITIES.STFL_FACILITY_NAME
			
			UNION
			
			SELECT STUDENT_MASTER.STMT_ADMISSION_NO AS [ID]
				--,STUDENT_ADMISSION.STAM_ROLL_NO
				,STUDENT_MASTER.STMT_FNAME + ' ' + STUDENT_MASTER.STMT_LNAME AS NAME
				,SUM(INSTALLMENTS_DETAILS.INSD_AMOUNT_PAID) AS [Fees Paid]
			--	,0 AS [Today Due]
				,ISNULL(SUM(INSTALLMENTS_DETAILS.INSD_INSTMNT_AMT) - SUM(INSTALLMENTS_DETAILS.INSD_AMOUNT_PAID) - SUM(INSTALLMENTS_DETAILS.INSD_DISCOUNT)-sum(ISNULL(INSD_CNCLD_AMT,0)), 0) AS [Total Outstanding]
				,ISNULL(SUM(INSTALLMENTS_DETAILS.INSD_INSTMNT_AMT), 0) AS [Total Fees]
				,ISNULL(SUM(INSTALLMENTS_DETAILS.INSD_DISCOUNT), 0) AS Discount
				,ISNULL(SUM(INSTALLMENTS_DETAILS.INSD_CNCLD_AMT),0) as "Cancelled Amount"
				,STANDARD.STD_NAME 
				,STREAM.STRM_NAME 
				,STUDENT_FACILITIES.STFL_FACILITY_NAME AS [Package Name]
				,STUDENT_MASTER.STMT_CONTACT_NO AS [Contact No]
				,STUDENT_MASTER.STMT_FATHER_CONTACT as[Parent No] 
				
				,STUDENT_MASTER.STMT_EMAIL_ID AS [Email ID]
				,BATCH.BTCH_NAME AS Batch
				,BRANCH_MASTER.BRCH_NAME AS Branch
				,STANDARD.STD_ID
				,STANDARD.STD_STREAM_ID
			FROM STUDENT
			INNER JOIN STUDENT_MASTER ON STUDENT.STUD_ADMISSION_NO = STUDENT_MASTER.STMT_ADMISSION_NO
			INNER JOIN BRANCH_MASTER ON STUDENT_MASTER.STMT_BRANCH_ID = BRANCH_MASTER.BRCH_ID
			INNER JOIN FEES ON STUDENT.STUD_FEES_ID = FEES.FEE_ID
			INNER JOIN STUDENT_ADMISSION ON STUDENT.STUD_ADMISSION_NO = STUDENT_ADMISSION.STAM_ADMISSION_NO
			INNER JOIN BATCH ON BATCH.BTCH_Id = STUDENT_ADMISSION.STAM_BATCH_ID
			INNER JOIN STANDARD ON STANDARD.STD_ID = STUDENT_ADMISSION.STAM_STD_ID
			INNER JOIN STREAM ON Standard.STD_STREAM_ID = STREAM.STRM_ID
			INNER JOIN STUDENT_FACILITIES ON STUDENT_ADMISSION.STAM_PACKAGE_ID = STUDENT_FACILITIES.STFL_PACKAGE_ID
				AND STUDENT_FACILITIES.STFL_ADMISSION_NO = STUDENT.STUD_ADMISSION_NO
			INNER JOIN INSTALLMENTS_DETAILS ON INSTALLMENTS_DETAILS.INSD_FACILITY_ID = STUDENT_FACILITIES.STFL_ID
			WHERE (STUDENT_MASTER.STMT_BRANCH_ID LIKE @Branch_Id)
			AND STREAM.STRM_ID like @stream 
			and STANDARD.STD_ID like @course 
			and BATCH.BTCH_Id like @batch
			
			GROUP BY STUDENT_MASTER.STMT_ADMISSION_NO
				,BRANCH_MASTER.BRCH_NAME
				--,STUDENT_ADMISSION.STAM_ROLL_NO
				,STUDENT_MASTER.STMT_FNAME
				,STUDENT_MASTER.STMT_MNAME
				,STUDENT_MASTER.STMT_LNAME
				,STANDARD.STD_NAME
				,STREAM.STRM_NAME
				,STUDENT_MASTER.STMT_CONTACT_NO 
				,STUDENT_MASTER.STMT_FATHER_CONTACT
				,STUDENT_MASTER.STMT_EMAIL_ID
				,BATCH.BTCH_NAME
				,STANDARD.STD_ID
				,STANDARD.STD_STREAM_ID
				,STUDENT_FACILITIES.STFL_FACILITY_NAME
			) AS OUTSTANDING_RESULT
			--where [Total Outstanding] <> 0.00
		GROUP BY [ID]
			--,[Roll No]
			,Name
			,STD_NAME 
			,[Package Name]
			,[Contact No]
			,[Parent No]
			,[Email ID]
			,Batch
			,Branch
			,STD_ID
			,STD_STREAM_ID
			,STRM_NAME
end
else
SELECT [ID]
			--,[Roll No]
			,Name
			,SUM([Fees Paid]) AS [Fees Paid]
			--,SUM([Today Due]) AS [Today Due]
			,SUM([Total Outstanding]) AS [Total Outstanding]
			,SUM([Total Fees]) AS [Total Fees]
			,SUM(Discount) AS Discount
			,sum([Cancelled Amount]) as CancelledAmount
			,STRM_NAME
			,STD_NAME 
			,[Package Name]
			,[Contact No]
			,[Email ID]
			,Batch
			,Branch
			,STD_ID
			,STD_STREAM_ID
		FROM (
			SELECT STUDENT_MASTER.STMT_ADMISSION_NO AS [ID]
				--,STUDENT_ADMISSION.STAM_ROLL_NO AS [Roll No]
				,STUDENT_MASTER.STMT_FNAME + ' ' + STUDENT_MASTER.STMT_LNAME AS NAME
				,0 AS [Fees Paid]
			--	,ISNULL(SUM(INSTALLMENTS_DETAILS.INSD_INSTMNT_AMT) - SUM(INSTALLMENTS_DETAILS.INSD_AMOUNT_PAID) - SUM(INSTALLMENTS_DETAILS.INSD_DISCOUNT)-sum(ISNULL(INSD_CNCLD_AMT,0)), 0) AS [Today Due]
				,0 AS [Total Outstanding]
				,0 AS [Total Fees]
				,0 AS Discount
				,0 as "Cancelled Amount"
				,STANDARD.STD_NAME 
				,STREAM.STRM_NAME 
				,STUDENT_FACILITIES.STFL_FACILITY_NAME AS [Package Name],
		
				STUDENT_MASTER.STMT_CONTACT_NO AS [Contact No]
				,STUDENT_MASTER.STMT_FATHER_CONTACT as[Parent No]
				,STUDENT_MASTER.STMT_EMAIL_ID AS [Email ID]
				,BATCH.BTCH_NAME AS Batch
				,BRANCH_MASTER.BRCH_NAME AS Branch
				,STANDARD.STD_ID
				,STANDARD.STD_STREAM_ID
			FROM STUDENT
			INNER JOIN STUDENT_MASTER ON STUDENT.STUD_ADMISSION_NO = STUDENT_MASTER.STMT_ADMISSION_NO
			INNER JOIN BRANCH_MASTER ON STUDENT_MASTER.STMT_BRANCH_ID = BRANCH_MASTER.BRCH_ID
			INNER JOIN FEES ON STUDENT.STUD_FEES_ID = FEES.FEE_ID
			INNER JOIN STUDENT_ADMISSION ON STUDENT.STUD_ADMISSION_NO = STUDENT_ADMISSION.STAM_ADMISSION_NO
			INNER JOIN BATCH ON BATCH.BTCH_Id = STUDENT_ADMISSION.STAM_BATCH_ID
			INNER JOIN STANDARD ON STANDARD.STD_ID = STUDENT_ADMISSION.STAM_STD_ID
			INNER JOIN STREAM ON Standard.STD_STREAM_ID = STREAM.STRM_ID
			INNER JOIN STUDENT_FACILITIES ON STUDENT_ADMISSION.STAM_PACKAGE_ID = STUDENT_FACILITIES.STFL_PACKAGE_ID
				AND STUDENT_FACILITIES.STFL_ADMISSION_NO = STUDENT.STUD_ADMISSION_NO
			INNER JOIN INSTALLMENTS_DETAILS ON INSTALLMENTS_DETAILS.INSD_FACILITY_ID = STUDENT_FACILITIES.STFL_ID
			WHERE (STUDENT_MASTER.STMT_BRANCH_ID LIKE @Branch_Id)
			AND STREAM.STRM_ID like @stream 
			and STANDARD.STD_ID like @course
			and BATCH.BTCH_Id like @batch
		    AND INSTALLMENTS_DETAILS.INSD_DATE <= @Date
		  
			GROUP BY STUDENT_MASTER.STMT_ADMISSION_NO
				,BRANCH_MASTER.BRCH_NAME
				--,STUDENT_ADMISSION.STAM_ROLL_NO
				,STUDENT_MASTER.STMT_FNAME
				,STUDENT_MASTER.STMT_MNAME
				,STUDENT_MASTER.STMT_LNAME
				,STANDARD.STD_NAME
				,STREAM.STRM_NAME
				,STUDENT_MASTER.STMT_CONTACT_NO
				,STUDENT_MASTER.STMT_FATHER_CONTACT
				,STUDENT_MASTER.STMT_EMAIL_ID
				,BATCH.BTCH_NAME
				,STANDARD.STD_ID
				,STANDARD.STD_STREAM_ID
				,STUDENT_FACILITIES.STFL_FACILITY_NAME
			
			UNION
			
			SELECT STUDENT_MASTER.STMT_ADMISSION_NO AS [ID]
				--,STUDENT_ADMISSION.STAM_ROLL_NO
				,STUDENT_MASTER.STMT_FNAME + ' ' + STUDENT_MASTER.STMT_LNAME AS NAME
				,SUM(INSTALLMENTS_DETAILS.INSD_AMOUNT_PAID) AS [Fees Paid]
				,0 AS [Today Due]
				--,ISNULL(SUM(INSTALLMENTS_DETAILS.INSD_INSTMNT_AMT) - SUM(INSTALLMENTS_DETAILS.INSD_AMOUNT_PAID) - SUM(INSTALLMENTS_DETAILS.INSD_DISCOUNT)-sum(ISNULL(INSD_CNCLD_AMT,0)), 0) AS [Total Outstanding]
				,ISNULL(SUM(INSTALLMENTS_DETAILS.INSD_INSTMNT_AMT), 0) AS [Total Fees]
				,ISNULL(SUM(INSTALLMENTS_DETAILS.INSD_DISCOUNT), 0) AS Discount
				,ISNULL(SUM(INSTALLMENTS_DETAILS.INSD_CNCLD_AMT),0) as "Cancelled Amount"
				,STANDARD.STD_NAME 
				,STREAM.STRM_NAME 
				,STUDENT_FACILITIES.STFL_FACILITY_NAME AS [Package Name]

				,STUDENT_MASTER.STMT_CONTACT_NO AS [Contact No]
				,STUDENT_MASTER.STMT_FATHER_CONTACT as[Parent No]
				,STUDENT_MASTER.STMT_EMAIL_ID AS [Email ID]
				,BATCH.BTCH_NAME AS Batch
				,BRANCH_MASTER.BRCH_NAME AS Branch
				,STANDARD.STD_ID
				,STANDARD.STD_STREAM_ID
			FROM STUDENT
			INNER JOIN STUDENT_MASTER ON STUDENT.STUD_ADMISSION_NO = STUDENT_MASTER.STMT_ADMISSION_NO
			INNER JOIN BRANCH_MASTER ON STUDENT_MASTER.STMT_BRANCH_ID = BRANCH_MASTER.BRCH_ID
			INNER JOIN FEES ON STUDENT.STUD_FEES_ID = FEES.FEE_ID
			INNER JOIN STUDENT_ADMISSION ON STUDENT.STUD_ADMISSION_NO = STUDENT_ADMISSION.STAM_ADMISSION_NO
			INNER JOIN BATCH ON BATCH.BTCH_Id = STUDENT_ADMISSION.STAM_BATCH_ID
			INNER JOIN STANDARD ON STANDARD.STD_ID = STUDENT_ADMISSION.STAM_STD_ID
			INNER JOIN STREAM ON Standard.STD_STREAM_ID = STREAM.STRM_ID
			INNER JOIN STUDENT_FACILITIES ON STUDENT_ADMISSION.STAM_PACKAGE_ID = STUDENT_FACILITIES.STFL_PACKAGE_ID
				AND STUDENT_FACILITIES.STFL_ADMISSION_NO = STUDENT.STUD_ADMISSION_NO
			INNER JOIN INSTALLMENTS_DETAILS ON INSTALLMENTS_DETAILS.INSD_FACILITY_ID = STUDENT_FACILITIES.STFL_ID
			WHERE (STUDENT_MASTER.STMT_BRANCH_ID LIKE @Branch_Id)
			AND STREAM.STRM_ID like @stream 
			and STANDARD.STD_ID like @course 
			and BATCH.BTCH_Id like @batch
			
			GROUP BY STUDENT_MASTER.STMT_ADMISSION_NO
				,BRANCH_MASTER.BRCH_NAME
				--,STUDENT_ADMISSION.STAM_ROLL_NO
				,STUDENT_MASTER.STMT_FNAME
				,STUDENT_MASTER.STMT_MNAME
				,STUDENT_MASTER.STMT_LNAME
				,STANDARD.STD_NAME
				,STREAM.STRM_NAME
				,STUDENT_MASTER.STMT_FATHER_CONTACT
				,STUDENT_MASTER.STMT_CONTACT_NO
				,STUDENT_MASTER.STMT_EMAIL_ID
				,BATCH.BTCH_NAME
				,STANDARD.STD_ID
				,STANDARD.STD_STREAM_ID
				,STUDENT_FACILITIES.STFL_FACILITY_NAME
			) AS OUTSTANDING_RESULT
			where [Total Outstanding] <> 0.00
		GROUP BY [ID]
			--,[Roll No]
			,Name
			,STD_NAME 
			,[Package Name]
			,[Contact No]
			,[Email ID]
			,Batch
			,Branch
			,STD_ID
			,STD_STREAM_ID
			,STRM_NAME
end
		SET @NUM_ERROR_CODE = 1;
	END TRY

	BEGIN CATCH
		EXECUTE sp_logError

		SET @NUM_ERROR_CODE = - 1
	END CATCH
END




