using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ClassManager.WinApp.UICommon
{
    public enum Forms
    {
        FrmEnquiryEntryForm,
        FrmRegistrationForm,
        FrmFeesPayment,
        FrmStandardMasterForm,
        FrmSubjectPackageMasterForm,
        FrmChangePassword,
        FrmAddUser,
        FrmReportViewer,
        FrmCollegeMaster,
        FrmLogin,
        FrmOutstandingFees,
        FrmCourses,
        FrmEnquiries,
        FrmPackagesView,
        FrmFollowUpVew,
        FrmRegistrationsView,
        FrmFollowUp,
        FrmFaculty,
        FrmImport,
        FrmFaculties,
        FrmTemplate,
        FrmSystemParam,
        FrmMarketing,
        FrmInstallmentDetails,
        FrmStudentInstallments,
        FrmStudent,
        FrmExpenses,
        FrmFeesCollectionReport,
        FrmFinance,
        FrmHolidayMaster,
        FrmAttendanceSheet,
        FrmDailyReport,
        FrmBranchMaster,
        FrmAttendanceLog,
        FrmIncomeEntry,
        FrmCommonPopup,
        FrmMigration,
        FrmSessionDetails,
        FrmDeleteStudent,
        FrmSettings,
        FrmOptionalSubject,
        FrmTestMaster,
        FrmStudentDetails,
        FrmSubjectMaster,
        FrmLecturesTimeTable,
        FrmMainForm,
        FrmInstructorDetails,
        FrmAssignPermissions,
        FrmSendNotification,
        FrmAccount,
        FrmViewCheques,
        FrmReport,
        FrmCreateAccount,
        FrmViewAccount,
        FrmViewTest,
        FrmUploadMarks,
        FrmViewSub,
        FrmAnyFollowUp,
        FrmAddFacilities,
        FrmLectureAttendance,
        FrmUserParameters,
        FrmRegistration,
        Commongrid,
        FrmSMS_Details,
        FrmAttendance,
        FrmExpiredRenewal,
        FrmImportRegistration,
        FrmQuickAdmission,
        FrmHelpForm,
        FrmDashBoard,
        FrmPackagePopup,
        FrmDetailsTran,
        FrmAbout,
        FrmManual,
        FrmTransfereAccount,
        FrmExpenseReport,
        FrmIncomeReport,
        FrmViewOutstanding,
        FrmEnquiryReport,
        FrmFollowReport,
        FrmStudentsReport,
        FrmExpiryReport,
        FrmViewScheduleLect,
        FrmActiveInactive,
        FrmViewDeleteFacilities,
        FrmExamReport,
        FrmBirthdayReport,
        FrmFollowupDetails,
        FrmActivityDetails,
        FrmOutstandingDueFollowup,
        FrmCheque
    }

    public enum FormOperation
    {        
        CREATE,
        EDIT,
        DELETE,
        VIEW

    }
   
}
